Rewrite init scripts and add missing nova-vnc-proxy.init
Signed-off-by: Julien Danjou <julien@danjou.info>

diff --git a/debian/nova-ajax-console-proxy.init b/debian/nova-ajax-console-proxy.init
--- a/debian/nova-ajax-console-proxy.init
+++ b/debian/nova-ajax-console-proxy.init
@@ -1,8 +1,8 @@
-#! /bin/sh
+#!/bin/sh
 ### BEGIN INIT INFO
 # Provides:          nova-ajax-console-proxy
-# Required-Start:    $remote_fs $syslog
-# Required-Stop:     $remote_fs $syslog
+# Required-Start:    $network $local_fs $remote_fs $syslog
+# Required-Stop:     $remote_fs
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: nova ajax console proxy
@@ -11,63 +11,87 @@
 #                    on compute nodes
 ### END INIT INFO
 
-set -e
+# Author: Julien Danjou <acid@debian.org>
 
+# PATH should only include /usr/* if it runs after the mountnfs.sh script
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+DESC="OpenStack Compute Ajax Console Proxy"
+NAME=nova-ajax-console-proxy
 DAEMON=/usr/bin/nova-ajax-console-proxy
 DAEMON_ARGS="--flagfile=/etc/nova/nova.conf"
-PIDFILE=/var/run/nova/nova-ajax-console-proxy.pid
+PIDFILE=/var/run/$NAME.pid
+SCRIPTNAME=/etc/init.d/$NAME
 
-ENABLED=true
+# Exit if the package is not installed
+[ -x $DAEMON ] || exit 0
 
-if test -f /etc/default/nova-ajax-console-proxy; then
-  . /etc/default/nova-ajax-console-proxy
-fi
-
-mkdir -p /var/run/nova
-chown nova:root /var/run/nova/
-
-mkdir -p /var/lock/nova
-chown nova:root /var/lock/nova/
-
-uid="$(getent passwd nova | cut -f3 -d:)"
-gid="$(getent passwd nova | cut -f4 -d:)"
+# Read configuration variable file if it is present
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
 . /lib/lsb/init-functions
 
-export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
+do_start()
+{
+	start-stop-daemon --start --background --chuid nova:nova --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+		|| return 1
+	start-stop-daemon --start --background --chuid nova:nova --quiet --pidfile $PIDFILE --exec $DAEMON -- \
+		$DAEMON_ARGS \
+		|| return 2
+}
 
-if ! [ -x ${DAEMON} ] ; then
-	exit 0
-fi
+do_stop()
+{
+	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+	RETVAL="$?"
+	[ "$RETVAL" = 2 ] && return 2
+	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+	[ "$?" = 2 ] && return 2
+	rm -f $PIDFILE
+	return "$RETVAL"
+}
 
 case "$1" in
   start)
-    test "$ENABLED" = "true" || exit 0
-    log_daemon_msg "Starting nova ajax console proxy" "nova-ajax-console-proxy"
-    start-stop-daemon --start --chdir /var/run --chuid ${uid}:${gid} -b -m --pidfile ${PIDFILE} --exec ${DAEMON} -- ${DAEMON_ARGS}
-    log_end_msg $?
-    ;;
+    log_daemon_msg "Starting $DESC " "$NAME"
+    do_start
+    case "$?" in
+		0|1) log_end_msg 0 ;;
+		2) log_end_msg 1 ;;
+	esac
+  ;;
   stop)
-    test "$ENABLED" = "true" || exit 0
-    log_daemon_msg "Stopping nova ajax console proxy" "nova-ajax-console-proxy"
-    start-stop-daemon --stop --oknodo --pidfile ${PIDFILE}
-    log_end_msg $?
-    ;;
-  restart|force-reload)
-    test "$ENABLED" = "true" || exit 1
-    $0 stop
-    sleep 1
-    $0 start
-    ;;
+	log_daemon_msg "Stopping $DESC" "$NAME"
+	do_stop
+	case "$?" in
+		0|1) log_end_msg 0 ;;
+		2) log_end_msg 1 ;;
+	esac
+	;;
   status)
-    test "$ENABLED" = "true" || exit 0
-    # This is to be fixed: it doesn't exist in Debian
-    status_of_proc -p $PIDFILE $DAEMON nova-ajax-console-proxy && exit 0 || exit $?
-    ;;
+       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+       ;;
+  restart|force-reload)
+	log_daemon_msg "Restarting $DESC" "$NAME"
+	do_stop
+	case "$?" in
+	  0|1)
+		do_start
+		case "$?" in
+			0) log_end_msg 0 ;;
+			1) log_end_msg 1 ;; # Old process is still running
+			*) log_end_msg 1 ;; # Failed to start
+		esac
+		;;
+	  *)
+		# Failed to stop
+		log_end_msg 1
+		;;
+	esac
+	;;
   *)
-    log_action_msg "Usage: $0 {start|stop|restart|force-reload|status}"
-    exit 1
-    ;;
+	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+	exit 3
+	;;
 esac
 
-exit 0
+:
